### ISSUE TITLE
The QtCreator change path

### ISSUE THREAD

**Issue by joaomedeirosr** [dracula/qtcreator#21]
Hello, Zeno Rocha, first thank you for the amazing theme. But when I trying to install the  Qtcreator drakula theme, I find some problems cuzz the path you suggest doesn't mach with the QtPath I don`t know if this happen only for me or other Ubuntu or another Linux distro users.

I opened this issue only cuzz I solved the pathing unconsistence. If anyone find the same path problem I suggest do this:

First step:
`git clone https://github.com/dracula/qtcreator.git`

Second step:
`cd qtcreator`

Third step:
`cp dracula.xml /usr/share/qtcreator/themes`

Now u only need go to Qt navite to: 
Tools -> Options ->Text Editor

btw i`m using ubuntu 22.04
![Captura de tela de 2024-01-11 16-31-08](https://github.com/dracula/qtcreator/assets/88453005/b2d06030-e807-48fa-a374-c36f9fc0e73d)

**Comment by ergenekonyigit** [comment]
Thank you for noticing the issue. Are these working steps?

#### Activating theme

1.  Move the `dracula.xml` file to `/usr/share/qtcreator/styles`.
2.  Move the `drakula.creatortheme` file to `/usr/share/qtcreator/themes`.
3.  Go to `Qt Creator -> Tools -> Options...`, click the `Environment` tab, and select `Drakula` in the `Theme`. Then click `Restart Now`.
4.  Go to `Qt Creator -> Tools -> Options...`, click the `Text Editor` tab, and select `Dracula` in the `Color Scheme`.

**Comment by joaomedeirosr** [comment]
@ergenekonyigit yes, that's it and after this the theme worked very well.

**Comment by ergenekonyigit** [comment]
Okay, I'm going to update the instructions. Thanks for help 🙌

**Comment by ergenekonyigit** [comment]
Updated https://github.com/dracula/qtcreator/commit/742336a9b3ff3c3a29ce5376f75b8ea9c9daf134
