### ISSUE TITLE
Welcome Screen broken on version 13.0.1

### ISSUE THREAD

**Issue by joka42** [dracula/qtcreator#22]
Ubuntu 22.04, QtCreator version 13.0.1 has a broken Welcome Screen, when using the theme:

![image](https://github.com/dracula/qtcreator/assets/68659955/2eb1ce28-bbaa-4c25-9dba-c6f160d989fd)

Buttons are still there, but not visible and can be clicked blindly.

in editing mode, everything works as expected.

**Comment by ergenekonyigit** [comment]
I am currently unable to access the Ubuntu environment. Could you create a PR for this issue?

**Comment by joka42** [comment]
I'd assume the QtCreator Version is more important, have you tested the latest version 13.0.1 (from the Qt Maintenance Tool)

I will test on windows 11 later today.

**Comment by joka42** [comment]
I just checked; it is the same on Windows 11. 

<img width="1013" alt="image" src="https://github.com/dracula/qtcreator/assets/68659955/e432cec6-e8a5-45f6-a40a-2b793d5f7935">

**Comment by joka42** [comment]
i found these changes in the newer themes:

in 
```
[General]
Includes=dark.figmatokens
```

file: dark.figmatokens:

```
; Qt Creator Color Tokens - dark mode

[Colors]

Token_Basic_Black=ff131313
Token_Basic_White=fff8f8f8

Token_Accent_Default=ff1F9B5D
Token_Accent_Muted=ff228C57
Token_Accent_Subtle=ff1F7A4D

Token_Background_Default=ff1f1f1f
Token_Background_Muted=ff262626
Token_Background_Subtle=ff2e2e2e

Token_Foreground_Default=ff474747
Token_Foreground_Muted=ff353535
Token_Foreground_Subtle=ff2A2A2A

Token_Text_Default=ffF8F8F8
Token_Text_Muted=ffAEAEAE
Token_Text_Subtle=ff595959

; Token_Text_Accent value from Figma is still too dark. Therefore, it is modified, here.
; Text (consisting of thin lines) needs to be substantially brighter than accent colors used for
; larger-area elements like the filled button.

; Token_Text_Accent=ff23B26A
Token_Text_Accent=ff30C06A

Token_Stroke_Strong=ffeeeeee
Token_Stroke_Muted=ff727272
Token_Stroke_Subtle=ff3a3a3a

Token_Notification_Alert=ffc98014
Token_Notification_Success=ff1f9b5d
Token_Notification_Neutral=ff016876
Token_Notification_Danger=ffb22245
```

that file must be in the themes folder along the theme file.

**Comment by joka42** [comment]
Please test, if the changes in #23 work for older versions as well. @ergenekonyigit

**Comment by ergenekonyigit** [comment]
Merged. Thank you 🙏

**Comment by shadowofdominance** [comment]
Thanks a lot I was very confused as to what was wrong, I came to the right place!
