### ISSUE TITLE
The theme makes QML syntax illegible

### ISSUE THREAD

**Issue by zeronote** [dracula/qtcreator#3]
As you can see from the attached screenshot it is very difficult to read qml code when the theme
is applied. Is there a way that let me contribute and fix this behaviour?
![dracula_qml](https://user-images.githubusercontent.com/597692/40501376-f481c98a-5f87-11e8-9f8b-ffe6c94df6e3.png)

**Comment by ergenekonyigit** [comment]
Fixed #5
