### ISSUE TITLE
Updated theme for Qt Creator 4.6.2

### ISSUE THREAD

**Issue by estherjk** [dracula/qtcreator#4]
Hi, I've [forked the repo](https://github.com/drejkim/qtcreator) and updated the theme for Qt Creator 4.6.2. Some of the styles, particularly for QML, were illegible and did not conform to the dracula color palette. I've attached a sample photo.

<img width="1552" alt="screen shot 2018-06-15 at 3 37 19 pm" src="https://user-images.githubusercontent.com/3721990/41492203-590574c0-70b2-11e8-8b39-4f7fc9ee3ced.png">

If it looks good, should I submit a pull request?

**Comment by ergenekonyigit** [comment]
Thank you so much 🙌 I think it looks good, what do you think? @zenorocha

**Comment by zenorocha** [comment]
Yeah, go ahead and send a PR. Good job 🎉
